Functionnal backlist system
CodingTrain/trainbot pull request #7
Opened 2020-03-23 18:52 UTC by informathemusic

Pls pull ;-;

2020-03-27 14:16 UTC, nobobo1234 reviewed
Please change the thing I mentioned

2020-03-27 14:16 UTC, nobobo1234 commented on src/bot.js
> -bot.blacklist = new Discord.Collection();
My actual goal with this was to add a list of users that are abusing the bot so they can't use it, but this is also a great idea!

2020-03-27 14:16 UTC, nobobo1234 commented on src/bot.js
> +})
Please add this to the command manager in the `handleCommand()` function. You should take a look into the structure of the bot before adding something :wink:

2020-03-27 14:17 UTC, nobobo1234 commented on src/bot.js
> +})
Also for the problem you mentioned, that can be solved by using async await

2020-03-27 18:09 UTC, nobobo1234 requested changes

2020-03-27 18:09 UTC, nobobo1234 commented on src/events/message.js
> +
As I said, please do this in the commands.handleCommand() function, not here :wink:

2020-03-27 18:20 UTC, informathemusic commented
I don't get how 🤔

2020-03-27 18:27 UTC, nobobo1234 commented
`src/managers/commands.js` is the place where the command is handled, please add your code there

2020-03-27 19:01 UTC, informathemusic commented
Ok I think I get it, will do this when I get my computer

On Fri, 27 Mar 2020, 19:27 Nola1222, <notifications@github.com> wrote:

> src/managers/commands.js is the place where the command is handled,
> please add your code there
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodingTrain/trainbot/pull/7#issuecomment-605200185>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJKBSXNVON2NVYJ2JMAKWXTRJTVZ3ANCNFSM4LSDA4DQ>
> .
>

2020-03-29 18:00 UTC, informathemusic commented
Moving to my other PR.

2020-03-29 18:00 UTC, closed without merging